services:
  - type: web
    name: nl-library-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Precisa ser configurado no dashboard do Render
      - key: JWT_SECRET
        sync: false  # Precisa ser configurado no dashboard do Render
      - key: JWT_EXPIRE
        value: 1d
